name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.8.1
  path_provider: ^2.0.8

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true